services:
  - type: web
    name: omnistream-telegram-bot
    runtime: node
    plan: free
    buildCommand: bash render-build.sh
    startCommand: node bot.mjs
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: ADMIN_ID
        value: "6204875999"
      - key: BOT_TOKEN
        sync: false
