services:
  - type: web
    name: omnistream-whatsapp-bot
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node index.js
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/src/server/.cache/puppeteer
